import type {IRole} from "@/common/interface";

export const ENEMY_BOOK: IRole[] = [
    {
        id: '1',
        name: '哥布林',
        hp: 1000,
        atk: 30,
        def: 6,
        speed: 102,
        crit: 6,
        dodge: 6,
        hp_up: 10,
        atk_up: 4,
        def_up: 1,
        speed_up: 2,
        crit_up: 1,
        dodge_up: 1,
        equipment: [],
        skillNames: ['打击'],
    },
    {
        id: '2',
        name: '史莱姆',
        hp: 1400,
        atk: 30,
        def: 10,
        speed: 101,
        crit: 6,
        dodge: 6,
        hp_up: 14,
        atk_up: 1,
        def_up: 1,
        speed_up: 2,
        crit_up: 1,
        dodge_up: 1,
        equipment: [],
        skillNames: ['打击'],
    },
    {
        id: '3',
        name: '骷髅兵',
        hp: 800,
        atk: 50,
        def: 6,
        speed: 103,
        crit: 6,
        dodge: 6,
        hp_up: 10,
        atk_up: 1,
        def_up: 1,
        speed_up: 2,
        crit_up: 1,
        dodge_up: 1,
        equipment: [],
        skillNames: ['打击'],
    },
    {
        id: '4',
        name: '魔王',
        hp: 2000,
        atk: 80,
        def: 10,
        speed: 100,
        crit: 6,
        dodge: 6,
        hp_up: 10,
        atk_up: 1,
        def_up: 1,
        speed_up: 2,
        crit_up: 1,
        dodge_up: 1,
        equipment: [],
        skillNames: ['打击'],
    },
]