import type {IRole} from "@/common/interface";

export const HERO_BOOK: IRole[] = [
    {
        name: '战士',
        hp: 1400,
        atk: 120,
        def: 14,
        speed: 102,
        crit: 10,
        dodge: 10,
        hp_up: 10,
        atk_up: 4,
        def_up: 1,
        speed_up: 2,
        crit_up: 1,
        dodge_up: 1,
        pos: 0,
        equipment: [],
        skillNames: ['打击', '旋风斩'],
    },
    {
        name: '法师',
        hp: 800,
        atk: 150,
        def: 6,
        speed: 102,
        crit: 10,
        dodge: 10,
        hp_up: 10,
        atk_up: 8,
        def_up: 1,
        speed_up: 2,
        crit_up: 1,
        dodge_up: 1,
        pos: 0,
        equipment: [],
        skillNames: ['打击', '恢复'],
    },
    {
        name: '刺客',
        hp: 1000,
        atk: 140,
        def: 10,
        speed: 106,
        crit: 10,
        dodge: 10,
        hp_up: 10,
        atk_up: 6,
        def_up: 1,
        speed_up: 2,
        crit_up: 1,
        dodge_up: 1,
        pos: 0,
        equipment: [],
        skillNames: ['打击', '弱点打击'],
    }
]